### ISSUE TITLE
Add include type name parameter

### ISSUE THREAD

**Issue by AndresMaca** [acupajoe/elasticstore#11]
Hi, due to the elastic search update, the include type name is set to false by default, to all the dudes with this problem it is easy solved adding this line in src/util/FirestoreHandler.ts:
![image](https://user-images.githubusercontent.com/20801961/62495274-03053e80-b79b-11e9-8885-c21bc2afc20f.png)

**Comment by acupajoe** [comment]
@AndresMaca thanks so much for figuring this out! I submitted a pull-request on your behalf and merged it. 

Keep on keepin' on my friend.

**Comment by AndresMaca** [comment]
> @AndresMaca thanks so much for figuring this out! I submitted a pull-request on your behalf and merged it.
> 
> Keep on keepin' on my friend.

Hi could you help me with the query for a "location" currently im doing queries like this and everything is going ok except of the location(geopoint): 

![image](https://user-images.githubusercontent.com/20801961/62665070-83ff3a00-b943-11e9-9f0e-2f21188d7fd2.png)

**Comment by acupajoe** [comment]
@AndresMaca the `body` key accepts a query that conforms to Elasticsearch's API so you can just structure an object that conforms to a location query [as seen here](https://www.elastic.co/blog/geo-location-and-search)!
