### ISSUE TITLE
Provide the "why"

### ISSUE THREAD

**Issue by imjared** [acupajoe/elasticstore#18]
Thanks for this project, there's some really interesting stuff in here and it's definitely a solution that I wouldn't have come to. I've read [your medium post](https://medium.com/@acupajoe/wondering-how-to-get-elasticsearch-and-firebases-firestore-to-play-nice-1d84553aa280) and I'm still trying to wrap my head around the "why".

If I'm understanding the project correctly, it seems that results are generated on-the-fly and on an as-needed basis. They're generated from ElasticSearch but I can't quite figure out what advantages this setup of putting data in Firestore has over ES. I imagine you could leverage Firebase auth/document control mechanisms but wondering if there's any other advantage to this setup that I'm just not grokking.

**Comment by acupajoe** [comment]
Howdy @imjared!

This project is meant to be supplemental to Firestore(FS) - in that data in ES would be duplicated from FS. The "why" is pretty simple -  I want to store data in firestore _and_ I want to be able to query *some* of that data using ES's query engine. So the combination of the two (should) give you the best of both worlds at the expense of added complexity to the project. 

The primary use case for me was for full text search on some of my documents - something that FS can not (and AFAIK will not) provide. The FS team actually recommends elasticsearch and algolia as options for doing this. (See: https://firebase.google.com/docs/firestore/solutions/search and https://github.com/googlearchive/flashlight) 

As I'm a self-hoster - I opted for the free solution with Elasticsearch and put this repo up as an adaptation of Google's original Flashlight project for Firebase.

Does that help? Or did I misunderstand your question?

**Comment by imjared** [comment]
This helps a bit. I have to admit I'm not super familiar with ES so the fact that you write about their "query engine" specifically vs ES as a service provides a bit of clarity. I think the piece for me that I'm having a hard time wrapping my head around is 

> I want to store data in firestore and I want to be able to query some of that data using ES's query engine

If you want to be able to query your Firestore data using ES, why did you find it valuable to only outsource the querying portion to ES versus using ES as a replicated datastore then querying against that directly?

My initial thoughts were something along the lines of using a cloud function to sync document data to ES [`.onUpdate()`](https://firebase.google.com/docs/reference/functions/providers_firestore_.documentbuilder.html#on-update) and I stumbled across your blog post when looking for info on people who might have successfully done something like this already. Obviously each application, developer, project, etc. has its own needs. Just trying to get some lessons learned before I have to painfully learn them myself :)

Thanks for the light speed response!

**Comment by acupajoe** [comment]
Ah! Now I gotcha. Yes. Firestore does a lot of heavy lifting for you out of the box that ES doesn't have. For example, my use case was a web app + mobile application. The FS SDK does query caching, offline storage, real-time updates, etc. etc. Implementing the same thing in ES would have been a lot more difficult (or, for some features, impossible).

As to the `.onUpdate()` handler. That's definitely an option!

However, this script offers the ability to import pre-existing data, do transforms, and isn't subject to the limit and the option to listen for searches and handle them in FS.  ([See here](https://github.com/acupajoe/elasticstore#making-searches-client-side)) 

If you only want to replicate data - then the cloud function option should work just fine for you!

**Comment by imjared** [comment]
Appreciate this!

**Comment by nikmartin** [comment]
To add to this another use case: we have a massive product catalog that we want to search in real time from our mobile app. Oour catalog is in firestore, but to get properly fast full text search, we index the catalog in ES.As a user searches, we write that search to firestore/search/<doc>/request document, and ES replies with search results (our product IDs) in the firestire/search/<doc>/response document, and we then have a trigger on those results that looks up the products and sends them to the client. Super handy!

**Comment by acupajoe** [comment]
@nikmartin thanks nick!
