### ISSUE TITLE
Include firestore map fields

### ISSUE THREAD

**Issue by zachgoz** [acupajoe/elasticstore#5]
I'm trying to use the example on my firestore db, but I'm getting stuck on how to use the transform or include. I have a map field on each document that I only want to include 2 fields on.. it has alot of other information that I don't want to send to elastic search. So if I take your example:
```
// firestore (in the console)
groups: {
  12341235: {
    title: "Group Name",                  // string
    description: "I'm a group",           // string
    location: "32,-74"                    // geo_point
    createdAt: "9/4/2018 00:00:00 GMT-0"  // date
    groupInfo: { 
        contact: 'joe',
        owner: 'sandy',
        ...a lot more group info that we dont want to include
  }
}
```
How would I only send groupInfo.contact and groupInfo.owner? I tried using either the include or transform like in your example but neither seem to work, I get a type error  [ts] Cannot find name 'doc'. [2304]": 
```
// references (in ./src/references.ts)
{
  ....
  {
    collection: "groups",
    index: "groups",
    type: "groups",
    mappings: {
      location: {
        contact: "string"
        owner: "string"
      }
    },
    transform: (data, parent) => ({
      ...data,
      contact: `${doc.groupInfo.contact}`
      owner: `${doc.groupInfo.owner}`
    }),
    include: ['groupInfo.contact', 'groupInfo.owner',
  },
  ....
}
```

**Comment by acupajoe** [comment]
Have you tried changing `doc` to `data` like your transform has listed? And just remove the `...data` to isolate it to the fields you want.

I would only do one of those functions (include vs. Transform). The transform offers the most flexibility.

**Comment by zachgoz** [comment]
I have tried with just the transform but it doesn't seem like the data param is providing the document data. I get an error saying it doesn't exist

**Comment by acupajoe** [comment]
So to clarify - the console logs `null` here and no data is returned?

`References.ts`
```
{
    collection: "groups",
    index: "groups",
    type: "groups",
    transform: (data, parent) => {
      console.log(data)
      return . {
          contact: `${data.groupInfo.contact}`
          owner: `${data.groupInfo.owner}`
      }
    })
}
```

**Comment by acupajoe** [comment]
Closing out of inactivity
