### ISSUE TITLE
How can we process Arrays from firestore

### ISSUE THREAD

**Issue by clacdesdoigts** [acupajoe/elasticstore#6]
Hi @acupajoe ,
Nice integration by the way, we're considering using in one of our projects.
Is there any chances to have a Firestore Array Type implemented as [Array datatype on ElasticSearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/array.html) ?

We're trying to transform it to keywords but is there any straightforward way to do it ?

Thanks

**Comment by acupajoe** [comment]
@clacdesdoigts glad to hear it's been a help!

Yes, arrays have to be of the same datatype according to Elasticsearch though. So provided you meet that requirement, the first document you insert into a new Elasticsearch index that contains an array will mark the type of that array for every additional document. 

i.e. if you insert `{ object1: { my_array: [ 1234, 5678 ] } }` as the first object in an index, `my_array` will be a typed `Integer` array, attempting to add an array to that key with anything other than `Integer` will fail.

So provided you're enforcing strict array types, there shouldn't be any additional config necessary. If you need to insert an array of objects try a [nested data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html)?
