### ISSUE TITLE
[illegal_argument_exception] Rejecting mapping update to [items] as the final mapping would have more than 1 type: [_doc, items] 

### ISSUE THREAD

**Issue by mayankjanmejay** [acupajoe/elasticstore#8]
Hello,

I am very new to Firebase Elastic search but It would seem like Firebase has changed something in their SDK because no matter what method I try to send data to Elastic Store I am getting this new error. I opened a ticket with Google and they aren't sure either what is happening. 

Please help

**Comment by acupajoe** [comment]
Hey! That looks like an elasticsearch error, not a Firestore error. When you create an index in elasticsearch it dynamically creates the fields and types unless otherwise specified.

It looks like you're trying to add a document with a conflicting type value.

```
// Insert and creat first object in index
var obj1 = { key1: "hello" }
// try to add with different type
var obj2 = { key1: 1234 }
// Fails because key1 expects a string
```

**Comment by mayankjanmejay** [comment]
There shouldn't be a data type clash because all the fields I am getting are all strings. This is my mapping. 

I apologize this is my first time working with Elastic Search. 
{
    "items": {
        "aliases": {},
        "mappings": {
            "properties": {
                "itemClass": {
                    "type": "text"
                },
                "itemCode": {
                    "type": "text"
                },
                "itemGroup": {
                    "type": "text"
                },
                "itemType": {
                    "type": "text"
                },
                "name": {
                    "type": "text"
                }
            }
        },
        "settings": {
            "index": {
                "creation_date": "1563308921659",
                "number_of_shards": "1",
                "number_of_replicas": "1",
                "uuid": "AggIu0BaTey0Tk7k9fYCTA",
                "version": {
                    "created": "7020099"
                },
                "provided_name": "items"
            }
        }
    }
}

**Comment by acupajoe** [comment]
Can you console log the doc that's being inserted and the last successful inserted doc?

**Comment by mayankjanmejay** [comment]
There has been no successful doc insert into this ES

**Comment by acupajoe** [comment]
Can you show me an object you're trying to insert then?

**Comment by mayankjanmejay** [comment]
I Did 
console.log("Item ->"+doc.data())


I got
Item ->[object Object]

This was the console.log when i was getting the same error but using cloud functions. 

Indexing item: { itemClass: 'MARFURI',
  itemCode: '111605CPB',
  itemGroup: 'PRODUSE CARNE',
  name: 'PORC : MASCA CU SORICI, FARA RAT / CONGELAT POLIBLOC',
  syncTime: Timestamp { _seconds: 1562936308, _nanoseconds: 527899000 },
  totalStock: 83.5,
  unit: 'KG',
 }

StatusCodeError: 400 - {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [items] as the final mapping would have more than 1 type: [_doc, item]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [items] as the final mapping would have more than 1 type: [_doc, item]"},"status":400}
    at new StatusCodeError (/srv/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/srv/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/srv/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/srv/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/srv/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/srv/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**Comment by mayankjanmejay** [comment]
I am also getting 


Error in `FS_MODIFIED` handler [doc@111210CPB]: [document_missing_exception] [items][111210CPB]: document missing, with { index_uuid="9tiLNgeIQGeJt4kaL1J9oA" & shard="0" & index="items" }

**Comment by acupajoe** [comment]
My guess would be that you don't specify `syncTime`, `totalStock` or `unit` in your Elasticsearch index but are trying to insert a document with those specified. You could try deleting the index and letting the first document insert specify it for you? (note there will be data loss in doing this)

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html

**Comment by mayankjanmejay** [comment]
You were right, once I deleted the index and let your app or es create the index it works great. Side question can I post ElasticStore to firebase cloud hosting or functions right?

**Comment by acupajoe** [comment]
Glad to hear it! You can to cloud hosting - not to functions. It has to be running constantly and functions only run on-demand.

**Comment by mayankjanmejay** [comment]
That is awesome Thank You very very much

**Comment by acupajoe** [comment]
@mayankjanmejay happy to help!
